name: Test project

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: workflow configure
        uses: actions/checkout@v2
      - name: Verify project
        run: mvn verify